### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by vukbgit** [slowprog/CopyFile#13]
Hello, you have a typo in README file, a missing colon between the two lines into File-to-file example:

{
    "extra": {
        "copy-file": {
            "dir/subdir/file1.txt": "web/other/file1.txt" HERE GOES THE MISSING COLON!
            "dir/subdir/file2.txt": "web/other/file_rename.txt"
        }
    }
}

thanks and keep up the good work

**Comment by slowprog** [comment]
Thanks! Fixed!
