### ISSUE TITLE
Exception if copy shall only be done in dev env

### ISSUE THREAD

**Issue by mgrundkoetter** [slowprog/CopyFile#14]
When using this package with `copy-file-dev` config only, it throws an exception when installing composer with `--no-dev`:

> [InvalidArgumentException]                                                     
> The dirs or files needs to be configured through the extra.copy-file setting.

When I then add a `copy-file` config to extras in composer.json, it throws another exception:

> [InvalidArgumentException]                                               
> The extra.copy-file must be hash like "{<dir_or_file_from>: <dir_to>}".

So using the copy file functionality is currently only possible with at least one config in production. It would be nice to also be able to have this working only in dev env.

**Comment by slowprog** [comment]
This is a good idea, but there is no time right now. If you make a pull request, it will be cool :)
